"""
Django settings for Exoticaproject project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import dj_database_url
from dotenv import load_dotenv
from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ImproperlyConfigured
from .unfold_config import UNFOLD
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production #
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gywh)zrdwb8ohd$l97a2mj_+u^pa6@hnsu$=)!ud(3l27%fe-y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Site settings for SEO
BASE_URL = 'https://luzmeloexoticfruits.com'

# SEO settings
SITE_ID = 1  # Necesario para django.contrib.sites

# SEO adicionales
SITE_NAME = 'L&M Exotic Fruits'
SITE_DESCRIPTION = 'Importadores y distribuidores mayoristas de frutas exóticas premium desde 2017 en España y Europa.'

# Configuración del correo para el formulario de contacto (usar el EMAIL_HOST_USER ya configurado)
CONTACT_EMAIL = 'import@luzmeloexoticfruits.com'  # Cambiar por el correo real

# Application definition

INSTALLED_APPS = [
    'autenticacion.apps.AutenticacionConfig',
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.inlines',
    'unfold.contrib.import_export',
    'unfold.contrib.simple_history',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Necesario para sitemaps
    'django.contrib.sitemaps',  # Añadimos soporte para sitemaps
    'django.contrib.humanize',
    'django_tables2',
    'crispy_forms',
    'crispy_bootstrap5',
    'import_export',
    'rest_framework',
    'django_extensions',
    'simple_history',
    'widget_tweaks',
    'comercial.apps.ComercialConfig',
    'productos.apps.ProductosConfig',
    'importacion.apps.ImportacionConfig',
    'captcha',  # Agregar captcha aquí
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'Exoticaproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'autenticacion', 'templates'),
            os.path.join(BASE_DIR, 'autenticacion', 'templates', 'registration'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Exoticaproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))
}
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'exotica',  # Nombre de tu base de datos
        'USER': 'postgres',  # Nombre de usuario de tu base de datos
        'PASSWORD': 'Sebastyk120',  # Contraseña del usuario de la base de datos
        'HOST': 'localhost',  # Deja esto como 'localhost' si estás ejecutando PostgreSQL localmente
        'PORT': '5433',  # Puerto de PostgreSQL (por defecto es 5432)
    }
}"""


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
LOGIN_URL = 'login'

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_ALLOW_ALL_ORIGINS = True

# Media files configuration
MEDIA_URL = '/media/'
if DEBUG:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    # En producción usamos la ruta montada
    MEDIA_ROOT = '/media'

# Añadir esta línea para que Whitenoise sirva archivos de medios en producción
WHITENOISE_ROOT = MEDIA_ROOT

# Configuración de carpeta para adjuntos de correos electrónicos
EMAIL_ATTACHMENTS_FOLDER = 'email_attachments'
EMAIL_ATTACHMENTS_ROOT = os.path.join(MEDIA_ROOT, EMAIL_ATTACHMENTS_FOLDER)

# Crear la carpeta de adjuntos si no existe al iniciar Django
def ensure_email_attachments_folder():
    """Crea la carpeta de adjuntos de correos si no existe"""
    try:
        os.makedirs(EMAIL_ATTACHMENTS_ROOT, exist_ok=True)
    except Exception as e:
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(f"No se pudo crear la carpeta de adjuntos de correos: {str(e)}")

# Ejecutar la función al cargar las configuraciones
ensure_email_attachments_folder()

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

ALLOWED_HOSTS = [
    'exoticfruits.up.railway.app',
    'localhost',
    'luzmeloexoticfruits.com',
    'www.luzmeloexoticfruits.com'
]

CSRF_TRUSTED_ORIGINS = ["https://*.up.railway.app", "https://*.luzmeloexoticfruits.com"]

CORS_ORIGINS_WHITELIST = [
    "https://exoticfruits.up.railway.app",
    "https://luzmeloexoticfruits.com",
    "https://www.luzmeloexoticfruits.com"
]
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# CONFIGURACIÓN MAIL CON MAILJET:
DEFAULT_FROM_EMAIL = "import@luzmeloexoticfruits.com"

# Usar el backend personalizado de Mailjet
EMAIL_BACKEND = 'Exoticaproject.backends.MailjetBackend'

try:
    MJ_APIKEY_PUBLIC = os.environ['MJ_APIKEY_PUBLIC']
    MJ_APIKEY_PRIVATE = os.environ['MJ_APIKEY_PRIVATE']
except KeyError as e:
    raise ImproperlyConfigured(f'La variable de entorno {e} no está definida para Mailjet')
ADMIN_SITE_NAME = 'Administración L&M Exótica'

# Aumentar límite para datos de upload (25MB para múltiples PDFs)
DATA_UPLOAD_MAX_MEMORY_SIZE = 26214400  # 25MB en bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 26214400  # 25MB en bytes

# Aumentar límite del tamaño del cuerpo de la petición
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Aumentar para manejar múltiples campos de PDFs

# Configuración de CAPTCHA
CAPTCHA_LENGTH = 5  # Longitud del captcha
CAPTCHA_FONT_SIZE = 50  # Tamaño de la fuente
CAPTCHA_LETTER_ROTATION = (-15, 15)  # Rotación de letras
CAPTCHA_BACKGROUND_COLOR = '#ffffff'  # Color de fondo
CAPTCHA_FOREGROUND_COLOR = '#001100'  # Color de las letras
CAPTCHA_TIMEOUT = 5  # Tiempo de validez en minutos


# Variables para PDF weasyprint
"""
RAILPACK_BUILD_APT_PACKAGES = libpango-1.0-0 libpangoft2-1.0-0 libharfbuzz0b libcairo2 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info libxml2-dev libxslt-dev
RAILPACK_DEPLOY_APT_PACKAGES = libpango-1.0-0 libpangoft2-1.0-0 libharfbuzz0b libcairo2 libgdk-pixbuf2.0-0 shared-mime-info
"""