# Generated by Django 5.1.7 on 2025-04-03 01:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('domicilio', models.CharField(max_length=255, verbose_name='Domicilio:')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('cif', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código  CIF')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('correos_adicionales', models.CharField(blank=True, max_length=255, null=True, verbose_name='Correos adicionales')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('dias_pago', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Días de pago')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Kilos Netos')),
                ('cajas_enviadas', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cajas Enviadas')),
                ('valor_x_caja_euro', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Caja Euro')),
                ('valor_x_producto', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Total Producto')),
                ('no_cajas_abono', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True, verbose_name='No Cajas Abono/Reclamación')),
                ('valor_abono_euro', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Valor Abono/Reclamación Euro')),
            ],
            options={
                'verbose_name': 'Detalle Venta',
                'verbose_name_plural': 'Detalles Ventas',
                'ordering': ['venta', 'presentacion'],
            },
        ),
        migrations.CreateModel(
            name='TranferenciasCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100, verbose_name='Referencia')),
                ('fecha_transferencia', models.DateField(verbose_name='Fecha Pago')),
                ('valor_transferencia', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor Pago Eur')),
                ('concepto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Concepto')),
            ],
            options={
                'verbose_name': 'Transferencia Cliente',
                'verbose_name_plural': 'Transferencias Cliente',
                'ordering': ['cliente', 'fecha_transferencia'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha Entrega')),
                ('fecha_vencimiento', models.DateField(editable=False, verbose_name='Fecha Vencimiento')),
                ('semana', models.CharField(blank=True, editable=False, null=True, verbose_name='Semana')),
                ('total_cajas_pedido', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Total Cajas')),
                ('numero_factura', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Número Factura')),
                ('iva', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='IVA 4%')),
                ('subtotal_factura', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal Factura')),
                ('valor_total_factura_euro', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Total Factura Euro')),
                ('valor_total_abono_euro', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Total Abono/Reclamacion Euro')),
                ('numero_nc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Abono/Reclamacion')),
                ('monto_pendiente', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Monto Pendiente')),
                ('pagado', models.BooleanField(default=False, editable=False, verbose_name='Pagado')),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BalanceCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Disponible Eur')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comercial.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Balance Cliente',
                'verbose_name_plural': 'Balances Clientes',
                'ordering': ['cliente', 'ultima_actualizacion'],
            },
        ),
    ]
