# Generated by Django 5.2 on 2025-04-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='token_acceso',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True, verbose_name='Token de Acceso'),
        ),
    ]
