# Generated by Django 5.2 on 2025-04-10 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje IVA'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='IVA'),
        ),
    ]
