# Generated by Django 5.2 on 2025-04-20 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_venta_porcentaje_iva_alter_venta_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_compra',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Compra'),
            preserve_default=False,
        ),
    ]
