# Generated by Django 5.2 on 2025-04-05 14:34

import comercial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_cliente_token_acceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correos_adicionales',
            field=models.CharField(blank=True, help_text='Ingrese múltiples correos separados por coma', max_length=255, null=True, validators=[comercial.models.validate_multiple_emails], verbose_name='Correos adicionales'),
        ),
    ]
