# Generated by Django 5.2 on 2025-04-23 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_venta_fecha_compra'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('prospect_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('prospect_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('prospect_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('prospect_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_validez', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], default='borrador', max_length=20)),
                ('terminos', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.cliente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comercial.cotizacion')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.presentacion')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotizaciones',
            },
        ),
    ]
