# Generated by Django 5.1.7 on 2025-03-21 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_alter_venta_iva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='cajas_envidadas',
            new_name='cajas_enviadas',
        ),
    ]
