# Generated by Django 5.1.7 on 2025-03-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_rename_cajas_envidadas_detalleventa_cajas_enviadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Monto Pendiente'),
        ),
    ]
