# Generated by Django 5.1.7 on 2025-03-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_venta_monto_pendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='valor_abono_euro',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Valor Abono/Reclamación Euro'),
        ),
    ]
