# Generated by Django 5.2 on 2025-05-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_remove_venta_fecha_compra_venta_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='domicilio_albaran',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Domicilio Albaran'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
