# Generated by Django 5.1.7 on 2025-03-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_alter_detalleventa_valor_abono_euro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='no_cajas_abono',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True, verbose_name='No Cajas Abono/Reclamación'),
        ),
    ]
