# Generated by Django 5.2.6 on 2025-09-16 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_cliente_domicilio_albaran_alter_cotizacion_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(choices=[('factura', 'Envío de Factura'), ('albaran', 'Envío de Albarán'), ('rectificativa', 'Envío de Factura Rectificativa'), ('albaran_aduana', 'Envío de Albarán a Aduana'), ('cotizacion', 'Envío de Cotización'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Proceso')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Envío')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto del Correo')),
                ('destinatarios', models.TextField(help_text='Lista de correos separados por coma', verbose_name='Destinatarios')),
                ('cuerpo_mensaje', models.TextField(verbose_name='Cuerpo del Mensaje')),
                ('documentos_adjuntos', models.TextField(blank=True, help_text='Nombres de archivos adjuntos separados por coma', null=True, verbose_name='Documentos Adjuntos')),
                ('estado_envio', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20, verbose_name='Estado del Envío')),
                ('respuesta_api', models.JSONField(blank=True, help_text='Respuesta completa de Mailjet API', null=True, verbose_name='Respuesta de la API')),
                ('mensaje_error', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.cliente', verbose_name='Cliente')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.cotizacion', verbose_name='Cotización Relacionada')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Envió')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.venta', verbose_name='Venta Relacionada')),
            ],
            options={
                'verbose_name': 'Log de Correo Electrónico',
                'verbose_name_plural': 'Logs de Correos Electrónicos',
                'ordering': ['-fecha_envio'],
                'indexes': [models.Index(fields=['proceso', 'fecha_envio'], name='comercial_e_proceso_20a977_idx'), models.Index(fields=['estado_envio', 'fecha_envio'], name='comercial_e_estado__34fb7b_idx'), models.Index(fields=['cliente', 'fecha_envio'], name='comercial_e_cliente_13df3d_idx')],
            },
        ),
    ]
