# Generated by Django 5.1.7 on 2025-03-30 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_alter_detalleventa_no_cajas_abono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Domicilio',
            new_name='domicilio',
        ),
    ]
