# Generated by Django 5.2.6 on 2025-09-19 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='valor_x_caja_euro',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor Caja Euro'),
        ),
    ]
