# Generated by Django 5.2.6 on 2025-09-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_alter_detalleventa_valor_x_caja_euro'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='origen',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Origen'),
        ),
    ]
