# Generated by Django 5.1.7 on 2025-03-30 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_rename_domicilio_cliente_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancecliente',
            name='saldo_disponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Disponible Eur'),
        ),
        migrations.AlterField(
            model_name='tranferenciascliente',
            name='fecha_transferencia',
            field=models.DateField(verbose_name='Fecha Pago'),
        ),
        migrations.AlterField(
            model_name='tranferenciascliente',
            name='valor_transferencia',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor Pago Eur'),
        ),
    ]
