# Generated by Django 5.1.7 on 2025-04-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_alter_balancecliente_saldo_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='numero_nc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Abono/Reclamacion'),
        ),
    ]
