# Generated by Django 5.2.7 on 2025-10-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0011_emaillog_adjuntos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='archivo_adjunto',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='documentos_adjuntos',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='adjunto_1',
            field=models.FileField(blank=True, null=True, upload_to='email_attachments/', verbose_name='Adjunto 1'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='adjunto_2',
            field=models.FileField(blank=True, null=True, upload_to='email_attachments/', verbose_name='Adjunto 2'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='adjunto_3',
            field=models.FileField(blank=True, null=True, upload_to='email_attachments/', verbose_name='Adjunto 3'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='adjunto_4',
            field=models.FileField(blank=True, null=True, upload_to='email_attachments/', verbose_name='Adjunto 4'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='adjunto_5',
            field=models.FileField(blank=True, null=True, upload_to='email_attachments/', verbose_name='Adjunto 5'),
        ),
    ]
