# Generated by Django 5.2.8 on 2025-11-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0012_remove_emaillog_archivo_adjunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranferenciascliente',
            name='referencia',
            field=models.CharField(max_length=100, unique=True, verbose_name='Referencia'),
        ),
    ]
