# Generated by Django 5.1.7 on 2025-04-03 01:11

import django.core.validators
import django.db.models.deletion
import importacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenciaAduana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('correos_adicionales', models.CharField(blank=True, max_length=255, null=True, verbose_name='Correos Adicionales')),
            ],
        ),
        migrations.CreateModel(
            name='AgenciaCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('correos_adicionales', models.CharField(blank=True, max_length=255, null=True, verbose_name='Correos Adicionales')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceExportador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Disponible')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Balance Exportador',
                'verbose_name_plural': 'Balances Exportador',
                'ordering': ['exportador', 'ultima_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.IntegerField(default=0, verbose_name='Stock Actual (Cajas)')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Stock Bodega',
                'verbose_name_plural': 'Stock Bodega',
                'ordering': ['presentacion'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Kilos Netos')),
                ('cajas_solicitadas', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cajas Solicitadas')),
                ('cajas_recibidas', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cajas Recibidas')),
                ('valor_x_caja_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Caja USD')),
                ('valor_x_producto', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Total Producto')),
                ('valor_x_producto_eur', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Total Producto EUR')),
                ('no_cajas_nc', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True, verbose_name='No Cajas NC')),
                ('valor_nc_usd', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Valor NC USD')),
                ('valor_nc_usd_manual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor NC USD Manual')),
            ],
            options={
                'verbose_name': 'Detalle Pedido',
                'verbose_name_plural': 'Detalles Pedido',
                'ordering': ['pedido', 'presentacion'],
            },
        ),
        migrations.CreateModel(
            name='Exportador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('correos_adicionales', models.CharField(blank=True, max_length=255, null=True, verbose_name='Correos Adicionales')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('datos_bancarios', models.CharField(blank=True, max_length=255, null=True, verbose_name='Datos Bancarios')),
                ('dias_credito', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Días Crédito')),
            ],
            options={
                'verbose_name': 'Exportador',
                'verbose_name_plural': 'Exportadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GastosAduana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=100, unique=True, verbose_name='Número Factura')),
                ('valor_gastos_aduana', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor Gastos Aduana Eur')),
                ('pagado', models.BooleanField(default=False, editable=False, verbose_name='Pagado')),
                ('numero_nota_credito', models.CharField(blank=True, max_length=100, null=True, verbose_name='# Abono/Reclamación')),
                ('valor_nota_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Abono/Reclamación')),
                ('monto_pendiente', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Monto Pendiente EUR')),
                ('conceptos', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Conceptos')),
            ],
            options={
                'verbose_name': 'Gastos Aduana',
                'verbose_name_plural': 'Gastos Aduana',
            },
        ),
        migrations.CreateModel(
            name='GastosCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Número Factura')),
                ('valor_gastos_carga', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor Gastos Carga USD')),
                ('valor_gastos_carga_eur', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor Gastos Carga EUR')),
                ('pagado', models.BooleanField(default=False, editable=False, verbose_name='Pagado')),
                ('valor_nota_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Nota Crédito USD')),
                ('numero_nota_credito', models.CharField(blank=True, max_length=100, null=True, verbose_name='Abono/Reclamación')),
                ('monto_pendiente', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Monto Pendiente USD')),
                ('conceptos', models.CharField(blank=True, max_length=500, null=True, verbose_name='Conceptos')),
            ],
            options={
                'verbose_name': 'Gastos Carga',
                'verbose_name_plural': 'Gastos Carga',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha Entrega')),
                ('semana', models.CharField(blank=True, editable=False, null=True, verbose_name='Semana')),
                ('awb', models.CharField(blank=True, default=None, max_length=12, null=True, validators=[importacion.models.validate_awb], verbose_name='AWB')),
                ('total_cajas_solicitadas', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Cajas Solicitadas')),
                ('total_cajas_recibidas', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Cajas Recibidas')),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Factura')),
                ('fecha_vencimiento', models.DateField(blank=True, editable=False, null=True, verbose_name='Vencimiento Factura')),
                ('valor_total_factura_usd', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Total Factura USD')),
                ('valor_total_nc_usd', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Total NC USD')),
                ('valor_factura_eur', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Total Factura EUR')),
                ('numero_nc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número NC')),
                ('estado_pedido', models.CharField(default='En Proceso', editable=False, verbose_name='Estado del Pedido')),
                ('pagado', models.BooleanField(default=False, editable=False, verbose_name='Pagado')),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('monto_pendiente', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Monto Pendiente USD')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TranferenciasAduana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100, verbose_name='Referencia')),
                ('fecha_transferencia', models.DateField(verbose_name='Fecha Transferencia')),
                ('valor_transferencia', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor Transferencia EUR')),
                ('concepto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Concepto')),
            ],
            options={
                'verbose_name': 'Transferencia Aduana',
                'verbose_name_plural': 'Transferencias Aduana',
                'ordering': ['agencia_aduana', 'fecha_transferencia'],
            },
        ),
        migrations.CreateModel(
            name='TranferenciasCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100, verbose_name='Referencia')),
                ('fecha_transferencia', models.DateField(verbose_name='Fecha Transferencia')),
                ('valor_transferencia', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor Transferencia USD')),
                ('valor_transferencia_eur', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor Transferencia EUR')),
                ('trm', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='TRM')),
                ('concepto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Concepto')),
            ],
            options={
                'verbose_name': 'Transferencia Carga',
                'verbose_name_plural': 'Transferencias Carga',
                'ordering': ['agencia_carga', 'fecha_transferencia'],
            },
        ),
        migrations.CreateModel(
            name='TranferenciasExportador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100, verbose_name='Referencia')),
                ('fecha_transferencia', models.DateField(verbose_name='Fecha Transferencia')),
                ('valor_transferencia', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor Transferencia USD')),
                ('valor_transferencia_eur', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor Transferencia EUR')),
                ('trm', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='TRM')),
                ('concepto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Concepto')),
            ],
            options={
                'verbose_name': 'Transferencia Exportador',
                'verbose_name_plural': 'Transferencias Exportador',
                'ordering': ['exportador', 'fecha_transferencia'],
            },
        ),
        migrations.CreateModel(
            name='BalanceGastosAduana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Disponible')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('agencia_aduana', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='importacion.agenciaaduana', verbose_name='Agencia Aduana')),
            ],
            options={
                'verbose_name': 'Balance Gastos Aduana',
                'verbose_name_plural': 'Balances Gastos Aduana',
                'ordering': ['agencia_aduana', 'ultima_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='BalanceGastosCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Disponible')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('agencia_carga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='importacion.agenciacarga', verbose_name='Agencia Carga')),
            ],
            options={
                'verbose_name': 'Balance Gastos Carga',
                'verbose_name_plural': 'Balances Gastos Carga',
                'ordering': ['agencia_carga', 'ultima_actualizacion'],
            },
        ),
    ]
