# Generated by Django 5.1.7 on 2025-04-03 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importacion', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.presentacion', verbose_name='Presentación'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.presentacion', verbose_name='Presentación'),
        ),
        migrations.AddField(
            model_name='balanceexportador',
            name='exportador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='importacion.exportador', verbose_name='Exportador'),
        ),
        migrations.AddField(
            model_name='gastosaduana',
            name='agencia_aduana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importacion.agenciaaduana', verbose_name='Agencia Aduana'),
        ),
        migrations.AddField(
            model_name='gastoscarga',
            name='agencia_carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importacion.agenciacarga', verbose_name='Agencia Carga'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='exportador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importacion.exportador', verbose_name='Exportador'),
        ),
        migrations.AddField(
            model_name='gastoscarga',
            name='pedidos',
            field=models.ManyToManyField(to='importacion.pedido', verbose_name='Pedidos'),
        ),
        migrations.AddField(
            model_name='gastosaduana',
            name='pedidos',
            field=models.ManyToManyField(to='importacion.pedido', verbose_name='Pedidos'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importacion.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='tranferenciasaduana',
            name='agencia_aduana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importacion.agenciaaduana', verbose_name='Agencia Aduana'),
        ),
        migrations.AddField(
            model_name='tranferenciascarga',
            name='agencia_carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importacion.agenciacarga', verbose_name='Agencia Carga'),
        ),
        migrations.AddField(
            model_name='tranferenciasexportador',
            name='exportador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importacion.exportador', verbose_name='Exportador'),
        ),
        migrations.AlterUniqueTogether(
            name='bodega',
            unique_together={('presentacion',)},
        ),
    ]
