# Generated by Django 5.1.7 on 2025-03-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='kilos',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Kilos Netos'),
        ),
    ]
