# Generated by Django 5.2 on 2025-04-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranferenciascarga',
            name='trm',
            field=models.DecimalField(blank=True, decimal_places=5, editable=False, max_digits=13, null=True, verbose_name='TRM'),
        ),
        migrations.AlterField(
            model_name='tranferenciasexportador',
            name='trm',
            field=models.DecimalField(blank=True, decimal_places=5, editable=False, max_digits=13, null=True, verbose_name='TRM'),
        ),
    ]
