# Generated by Django 5.1.7 on 2025-03-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0003_alter_detallepedido_kilos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='monto_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Monto Pendiente USD'),
        ),
    ]
