# Generated by Django 5.2.7 on 2025-10-20 20:16

import importacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0003_alter_tranferenciascarga_trm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenciaaduana',
            name='correos_adicionales',
            field=models.CharField(blank=True, help_text='Ingrese múltiples correos separados por coma', max_length=255, null=True, validators=[importacion.models.validate_multiple_emails], verbose_name='Correos Adicionales'),
        ),
        migrations.AlterField(
            model_name='agenciacarga',
            name='correos_adicionales',
            field=models.CharField(blank=True, help_text='Ingrese múltiples correos separados por coma', max_length=255, null=True, validators=[importacion.models.validate_multiple_emails], verbose_name='Correos Adicionales'),
        ),
        migrations.AlterField(
            model_name='exportador',
            name='correos_adicionales',
            field=models.CharField(blank=True, help_text='Ingrese múltiples correos separados por coma', max_length=255, null=True, validators=[importacion.models.validate_multiple_emails], verbose_name='Correos Adicionales'),
        ),
    ]
