# Generated by Django 5.1.7 on 2025-03-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0004_pedido_monto_pendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Vencimiento Factura'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total_factura_usd',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Total Factura USD'),
        ),
    ]
