# Generated by Django 5.2.8 on 2025-11-16 19:45

import importacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0004_alter_agenciaaduana_correos_adicionales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastosaduana',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=importacion.models.upload_to_aduana, verbose_name='Archivo PDF'),
        ),
        migrations.AddField(
            model_name='gastoscarga',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=importacion.models.upload_to_carga, verbose_name='Archivo PDF'),
        ),
    ]
