# Generated by Django 5.1.7 on 2025-03-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0005_alter_pedido_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor_total_factura_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Total Factura USD'),
        ),
    ]
