# Generated by Django 5.2.8 on 2025-11-17 21:29

import importacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0005_gastosaduana_pdf_file_gastoscarga_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastosaduana',
            name='pdf_file_rectificativa',
            field=models.FileField(blank=True, null=True, upload_to=importacion.models.upload_to_aduana, verbose_name='Archivo PDF Factura Rectificativa'),
        ),
        migrations.AddField(
            model_name='gastoscarga',
            name='pdf_file_rectificativa',
            field=models.FileField(blank=True, null=True, upload_to=importacion.models.upload_to_carga, verbose_name='Archivo PDF Factura Rectificativa'),
        ),
        migrations.AlterField(
            model_name='gastosaduana',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=importacion.models.upload_to_aduana, verbose_name='Archivo PDF Factura Principal'),
        ),
        migrations.AlterField(
            model_name='gastoscarga',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=importacion.models.upload_to_carga, verbose_name='Archivo PDF Factura Principal'),
        ),
    ]
