# Generated by Django 5.2.8 on 2025-11-23 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0006_gastosaduana_pdf_file_rectificativa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastosaduana',
            options={'ordering': ['pedidos__fecha_entrega', 'id'], 'verbose_name': 'Gastos Aduana', 'verbose_name_plural': 'Gastos Aduana'},
        ),
        migrations.AlterModelOptions(
            name='gastoscarga',
            options={'ordering': ['pedidos__fecha_entrega', 'id'], 'verbose_name': 'Gastos Carga', 'verbose_name_plural': 'Gastos Carga'},
        ),
    ]
