# Generated by Django 5.1.7 on 2025-03-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0006_alter_pedido_valor_total_factura_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastosaduana',
            name='monto_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Monto Pendiente EUR'),
        ),
        migrations.AlterField(
            model_name='gastosaduana',
            name='numero_factura',
            field=models.CharField(max_length=100, verbose_name='Número Factura'),
        ),
        migrations.AlterField(
            model_name='gastosaduana',
            name='numero_nota_credito',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='# Abono/Reclamación'),
        ),
        migrations.AlterField(
            model_name='gastosaduana',
            name='valor_nota_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Abono/Reclamación'),
        ),
    ]
