# Generated by Django 5.1.7 on 2025-03-21 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0007_gastosaduana_monto_pendiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoscarga',
            name='monto_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Monto Pendiente USD'),
        ),
        migrations.AlterField(
            model_name='gastoscarga',
            name='valor_gastos_carga',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor Gastos Carga USD'),
        ),
    ]
