# Generated by Django 5.1.7 on 2025-03-21 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0008_gastoscarga_monto_pendiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoscarga',
            name='valor_gastos_carga_eur',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor Gastos Carga EUR'),
        ),
    ]
