# Generated by Django 5.1.7 on 2025-03-21 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0009_alter_gastoscarga_valor_gastos_carga_eur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoscarga',
            name='valor_gastos_carga_eur',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor Gastos Carga EUR'),
        ),
    ]
