# Generated by Django 5.1.7 on 2025-03-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0010_alter_gastoscarga_valor_gastos_carga_eur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoscarga',
            name='valor_nota_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Nota Crédito USD'),
        ),
    ]
