# Generated by Django 5.1.7 on 2025-03-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0011_alter_gastoscarga_valor_nota_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='stock_actual',
            field=models.IntegerField(default=0, verbose_name='Stock Actual (Cajas)'),
        ),
    ]
