# Generated by Django 5.1.7 on 2025-03-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0012_alter_bodega_stock_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosaduana',
            name='numero_factura',
            field=models.CharField(max_length=100, unique=True, verbose_name='Número Factura'),
        ),
    ]
