# Generated by Django 5.1.7 on 2025-03-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0013_alter_gastosaduana_numero_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosaduana',
            name='conceptos',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Conceptos'),
        ),
    ]
