# Generated by Django 5.1.7 on 2025-03-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0014_alter_gastosaduana_conceptos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosaduana',
            name='conceptos',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Conceptos'),
        ),
    ]
