# Generated by Django 5.1.7 on 2025-03-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0015_alter_gastosaduana_conceptos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoscarga',
            name='conceptos',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Conceptos'),
        ),
        migrations.AlterField(
            model_name='gastoscarga',
            name='numero_factura',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='Número Factura'),
        ),
    ]
