# Generated by Django 5.1.7 on 2025-03-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0016_alter_gastoscarga_conceptos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='no_cajas_nc',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True, verbose_name='No Cajas NC'),
        ),
    ]
