# Generated by Django 5.1.7 on 2025-04-01 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0017_alter_detallepedido_no_cajas_nc'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='valor_x_producto_eur',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Total Producto EUR'),
        ),
        migrations.AlterField(
            model_name='tranferenciasaduana',
            name='valor_transferencia',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor Transferencia EUR'),
        ),
    ]
