# Generated by Django 5.1.7 on 2025-04-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0018_detallepedido_valor_x_producto_eur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='valor_nc_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor NC USD'),
        ),
    ]
