# Generated by Django 5.1.7 on 2025-04-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0019_alter_detallepedido_valor_nc_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='es_valor_nc_manual',
            field=models.BooleanField(default=False, editable=False, verbose_name='Valor NC Manual'),
        ),
    ]
