# Generated by Django 5.1.7 on 2025-04-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0020_detallepedido_es_valor_nc_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='es_valor_nc_manual',
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='valor_nc_usd',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Valor NC USD'),
        ),
    ]
