# Generated by Django 5.1.7 on 2025-04-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0021_remove_detallepedido_es_valor_nc_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='valor_nc_usd_manual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor NC USD Manual'),
        ),
    ]
