# Generated by Django 5.1.7 on 2025-03-19 20:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
        ('importacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(15.1)], verbose_name='Kilos')),
                ('fruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.fruta')),
            ],
            options={
                'verbose_name': 'Presentaciónes',
                'ordering': ['fruta__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ListaPreciosVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_euro', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='Precio Euro')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha Ultima Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.cliente', verbose_name='Cliente')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.presentacion')),
            ],
            options={
                'verbose_name': 'Lista de Precios Cliente',
                'verbose_name_plural': 'Listas de Precio Clientes',
                'ordering': ['cliente', 'presentacion'],
                'unique_together': {('presentacion', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='ListaPreciosImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='Precio USD')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha Ultima Actualización')),
                ('exportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importacion.exportador', verbose_name='Exportador')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.presentacion')),
            ],
            options={
                'verbose_name': 'Lista de Precios Exportador',
                'verbose_name_plural': 'Listas de Precio Exportador',
                'ordering': ['exportador', 'presentacion'],
                'unique_together': {('presentacion', 'exportador')},
            },
        ),
    ]
