# Generated by Django 5.1.7 on 2025-03-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presentacion',
            unique_together={('fruta', 'kilos')},
        ),
    ]
