# Generated by Django 5.2 on 2025-05-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruta',
            options={'ordering': ['nombre'], 'verbose_name': 'Fruta', 'verbose_name_plural': 'Frutas'},
        ),
        migrations.AddField(
            model_name='fruta',
            name='beneficios',
            field=models.TextField(blank=True, help_text='Beneficios nutricionales o para la salud', null=True),
        ),
        migrations.AddField(
            model_name='fruta',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='fruta',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='fruta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='frutas/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='fruta',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Descripción corta para motores de búsqueda (máx. 160 caracteres)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='fruta',
            name='origen',
            field=models.CharField(blank=True, help_text='País o región de origen', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fruta',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigable para el producto (se genera automáticamente)', null=True, unique=True),
        ),
    ]
